// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: src/proto/arg.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cols          []*TableCol            `protobuf:"bytes,1,rep,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTable) Reset() {
	*x = CreateTable{}
	mi := &file_src_proto_arg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTable) ProtoMessage() {}

func (x *CreateTable) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_arg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTable.ProtoReflect.Descriptor instead.
func (*CreateTable) Descriptor() ([]byte, []int) {
	return file_src_proto_arg_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTable) GetCols() []*TableCol {
	if x != nil {
		return x.Cols
	}
	return nil
}

type TableCol struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableCol) Reset() {
	*x = TableCol{}
	mi := &file_src_proto_arg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableCol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableCol) ProtoMessage() {}

func (x *TableCol) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_arg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableCol.ProtoReflect.Descriptor instead.
func (*TableCol) Descriptor() ([]byte, []int) {
	return file_src_proto_arg_proto_rawDescGZIP(), []int{1}
}

func (x *TableCol) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TableCol) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type Insert struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Val           map[string]*structpb.Value `protobuf:"bytes,1,rep,name=val,proto3" json:"val,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Insert) Reset() {
	*x = Insert{}
	mi := &file_src_proto_arg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Insert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Insert) ProtoMessage() {}

func (x *Insert) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_arg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Insert.ProtoReflect.Descriptor instead.
func (*Insert) Descriptor() ([]byte, []int) {
	return file_src_proto_arg_proto_rawDescGZIP(), []int{2}
}

func (x *Insert) GetVal() map[string]*structpb.Value {
	if x != nil {
		return x.Val
	}
	return nil
}

type Delete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Col           string                 `protobuf:"bytes,1,opt,name=col,proto3" json:"col,omitempty"`
	Val           *structpb.Value        `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Delete) Reset() {
	*x = Delete{}
	mi := &file_src_proto_arg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Delete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Delete) ProtoMessage() {}

func (x *Delete) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_arg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Delete.ProtoReflect.Descriptor instead.
func (*Delete) Descriptor() ([]byte, []int) {
	return file_src_proto_arg_proto_rawDescGZIP(), []int{3}
}

func (x *Delete) GetCol() string {
	if x != nil {
		return x.Col
	}
	return ""
}

func (x *Delete) GetVal() *structpb.Value {
	if x != nil {
		return x.Val
	}
	return nil
}

type Update struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Col           string                     `protobuf:"bytes,1,opt,name=col,proto3" json:"col,omitempty"`
	Val           *structpb.Value            `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
	Args          map[string]*structpb.Value `protobuf:"bytes,3,rep,name=args,proto3" json:"args,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Update) Reset() {
	*x = Update{}
	mi := &file_src_proto_arg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Update) ProtoMessage() {}

func (x *Update) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_arg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Update.ProtoReflect.Descriptor instead.
func (*Update) Descriptor() ([]byte, []int) {
	return file_src_proto_arg_proto_rawDescGZIP(), []int{4}
}

func (x *Update) GetCol() string {
	if x != nil {
		return x.Col
	}
	return ""
}

func (x *Update) GetVal() *structpb.Value {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *Update) GetArgs() map[string]*structpb.Value {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_src_proto_arg_proto protoreflect.FileDescriptor

const file_src_proto_arg_proto_rawDesc = "" +
	"\n" +
	"\x13src/proto/arg.proto\x12\x05proto\x1a\x1cgoogle/protobuf/struct.proto\"2\n" +
	"\vCreateTable\x12#\n" +
	"\x04cols\x18\x01 \x03(\v2\x0f.proto.TableColR\x04cols\"2\n" +
	"\bTableCol\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"\x82\x01\n" +
	"\x06Insert\x12(\n" +
	"\x03val\x18\x01 \x03(\v2\x16.proto.Insert.ValEntryR\x03val\x1aN\n" +
	"\bValEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01\"D\n" +
	"\x06Delete\x12\x10\n" +
	"\x03col\x18\x01 \x01(\tR\x03col\x12(\n" +
	"\x03val\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x03val\"\xc2\x01\n" +
	"\x06Update\x12\x10\n" +
	"\x03col\x18\x01 \x01(\tR\x03col\x12(\n" +
	"\x03val\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x03val\x12+\n" +
	"\x04args\x18\x03 \x03(\v2\x17.proto.Update.ArgsEntryR\x04args\x1aO\n" +
	"\tArgsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12,\n" +
	"\x05value\x18\x02 \x01(\v2\x16.google.protobuf.ValueR\x05value:\x028\x01B\x13Z\x11./src/proto;protob\x06proto3"

var (
	file_src_proto_arg_proto_rawDescOnce sync.Once
	file_src_proto_arg_proto_rawDescData []byte
)

func file_src_proto_arg_proto_rawDescGZIP() []byte {
	file_src_proto_arg_proto_rawDescOnce.Do(func() {
		file_src_proto_arg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_arg_proto_rawDesc), len(file_src_proto_arg_proto_rawDesc)))
	})
	return file_src_proto_arg_proto_rawDescData
}

var file_src_proto_arg_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_src_proto_arg_proto_goTypes = []any{
	(*CreateTable)(nil),    // 0: proto.CreateTable
	(*TableCol)(nil),       // 1: proto.TableCol
	(*Insert)(nil),         // 2: proto.Insert
	(*Delete)(nil),         // 3: proto.Delete
	(*Update)(nil),         // 4: proto.Update
	nil,                    // 5: proto.Insert.ValEntry
	nil,                    // 6: proto.Update.ArgsEntry
	(*structpb.Value)(nil), // 7: google.protobuf.Value
}
var file_src_proto_arg_proto_depIdxs = []int32{
	1, // 0: proto.CreateTable.cols:type_name -> proto.TableCol
	5, // 1: proto.Insert.val:type_name -> proto.Insert.ValEntry
	7, // 2: proto.Delete.val:type_name -> google.protobuf.Value
	7, // 3: proto.Update.val:type_name -> google.protobuf.Value
	6, // 4: proto.Update.args:type_name -> proto.Update.ArgsEntry
	7, // 5: proto.Insert.ValEntry.value:type_name -> google.protobuf.Value
	7, // 6: proto.Update.ArgsEntry.value:type_name -> google.protobuf.Value
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_src_proto_arg_proto_init() }
func file_src_proto_arg_proto_init() {
	if File_src_proto_arg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_arg_proto_rawDesc), len(file_src_proto_arg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_proto_arg_proto_goTypes,
		DependencyIndexes: file_src_proto_arg_proto_depIdxs,
		MessageInfos:      file_src_proto_arg_proto_msgTypes,
	}.Build()
	File_src_proto_arg_proto = out.File
	file_src_proto_arg_proto_goTypes = nil
	file_src_proto_arg_proto_depIdxs = nil
}
