// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: src/proto/catalog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Catalogs holds a list of catalog entries.
type Catalogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Catalogs      []*Catalog             `protobuf:"bytes,1,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalogs) Reset() {
	*x = Catalogs{}
	mi := &file_src_proto_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalogs) ProtoMessage() {}

func (x *Catalogs) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalogs.ProtoReflect.Descriptor instead.
func (*Catalogs) Descriptor() ([]byte, []int) {
	return file_src_proto_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Catalogs) GetCatalogs() []*Catalog {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

// Catalog represents a mapping (e.g., table or column).
type Catalog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_src_proto_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_src_proto_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Catalog) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Catalog) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_src_proto_catalog_proto protoreflect.FileDescriptor

const file_src_proto_catalog_proto_rawDesc = "" +
	"\n" +
	"\x17src/proto/catalog.proto\x12\x05proto\"6\n" +
	"\bCatalogs\x12*\n" +
	"\bcatalogs\x18\x01 \x03(\v2\x0e.proto.CatalogR\bcatalogs\"/\n" +
	"\aCatalog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05valueB\x13Z\x11./src/proto;protob\x06proto3"

var (
	file_src_proto_catalog_proto_rawDescOnce sync.Once
	file_src_proto_catalog_proto_rawDescData []byte
)

func file_src_proto_catalog_proto_rawDescGZIP() []byte {
	file_src_proto_catalog_proto_rawDescOnce.Do(func() {
		file_src_proto_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_catalog_proto_rawDesc), len(file_src_proto_catalog_proto_rawDesc)))
	})
	return file_src_proto_catalog_proto_rawDescData
}

var file_src_proto_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_proto_catalog_proto_goTypes = []any{
	(*Catalogs)(nil), // 0: proto.Catalogs
	(*Catalog)(nil),  // 1: proto.Catalog
}
var file_src_proto_catalog_proto_depIdxs = []int32{
	1, // 0: proto.Catalogs.catalogs:type_name -> proto.Catalog
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_proto_catalog_proto_init() }
func file_src_proto_catalog_proto_init() {
	if File_src_proto_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_catalog_proto_rawDesc), len(file_src_proto_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_proto_catalog_proto_goTypes,
		DependencyIndexes: file_src_proto_catalog_proto_depIdxs,
		MessageInfos:      file_src_proto_catalog_proto_msgTypes,
	}.Build()
	File_src_proto_catalog_proto = out.File
	file_src_proto_catalog_proto_goTypes = nil
	file_src_proto_catalog_proto_depIdxs = nil
}
