// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.3
// source: src/proto/catalog.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Catalogs holds a list of catalog entries.
type Catalogs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Catalogs []*Catalog `protobuf:"bytes,1,rep,name=catalogs,proto3" json:"catalogs,omitempty"`
}

func (x *Catalogs) Reset() {
	*x = Catalogs{}
	mi := &file_src_proto_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalogs) ProtoMessage() {}

func (x *Catalogs) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalogs.ProtoReflect.Descriptor instead.
func (*Catalogs) Descriptor() ([]byte, []int) {
	return file_src_proto_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Catalogs) GetCatalogs() []*Catalog {
	if x != nil {
		return x.Catalogs
	}
	return nil
}

// Catalog represents a mapping (e.g., table or column).
type Catalog struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Catalog) Reset() {
	*x = Catalog{}
	mi := &file_src_proto_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Catalog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Catalog) ProtoMessage() {}

func (x *Catalog) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Catalog.ProtoReflect.Descriptor instead.
func (*Catalog) Descriptor() ([]byte, []int) {
	return file_src_proto_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *Catalog) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Catalog) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_src_proto_catalog_proto protoreflect.FileDescriptor

var file_src_proto_catalog_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x36, 0x0a, 0x08, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x12, 0x2a, 0x0a, 0x08,
	0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x52, 0x08,
	0x63, 0x61, 0x74, 0x61, 0x6c, 0x6f, 0x67, 0x73, 0x22, 0x2f, 0x0a, 0x07, 0x43, 0x61, 0x74, 0x61,
	0x6c, 0x6f, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x13, 0x5a, 0x11, 0x2e, 0x2f, 0x73,
	0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_proto_catalog_proto_rawDescOnce sync.Once
	file_src_proto_catalog_proto_rawDescData = file_src_proto_catalog_proto_rawDesc
)

func file_src_proto_catalog_proto_rawDescGZIP() []byte {
	file_src_proto_catalog_proto_rawDescOnce.Do(func() {
		file_src_proto_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_proto_catalog_proto_rawDescData)
	})
	return file_src_proto_catalog_proto_rawDescData
}

var file_src_proto_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_proto_catalog_proto_goTypes = []any{
	(*Catalogs)(nil), // 0: proto.Catalogs
	(*Catalog)(nil),  // 1: proto.Catalog
}
var file_src_proto_catalog_proto_depIdxs = []int32{
	1, // 0: proto.Catalogs.catalogs:type_name -> proto.Catalog
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_proto_catalog_proto_init() }
func file_src_proto_catalog_proto_init() {
	if File_src_proto_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_proto_catalog_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_proto_catalog_proto_goTypes,
		DependencyIndexes: file_src_proto_catalog_proto_depIdxs,
		MessageInfos:      file_src_proto_catalog_proto_msgTypes,
	}.Build()
	File_src_proto_catalog_proto = out.File
	file_src_proto_catalog_proto_rawDesc = nil
	file_src_proto_catalog_proto_goTypes = nil
	file_src_proto_catalog_proto_depIdxs = nil
}
