// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: src/proto/wal.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WalRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lsn           uint64                 `protobuf:"varint,1,opt,name=lsn,proto3" json:"lsn,omitempty"`
	Op            uint32                 `protobuf:"varint,2,opt,name=op,proto3" json:"op,omitempty"`
	TableId       uint32                 `protobuf:"varint,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WalRecord) Reset() {
	*x = WalRecord{}
	mi := &file_src_proto_wal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WalRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalRecord) ProtoMessage() {}

func (x *WalRecord) ProtoReflect() protoreflect.Message {
	mi := &file_src_proto_wal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalRecord.ProtoReflect.Descriptor instead.
func (*WalRecord) Descriptor() ([]byte, []int) {
	return file_src_proto_wal_proto_rawDescGZIP(), []int{0}
}

func (x *WalRecord) GetLsn() uint64 {
	if x != nil {
		return x.Lsn
	}
	return 0
}

func (x *WalRecord) GetOp() uint32 {
	if x != nil {
		return x.Op
	}
	return 0
}

func (x *WalRecord) GetTableId() uint32 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *WalRecord) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_src_proto_wal_proto protoreflect.FileDescriptor

const file_src_proto_wal_proto_rawDesc = "" +
	"\n" +
	"\x13src/proto/wal.proto\x12\x05proto\"\\\n" +
	"\tWalRecord\x12\x10\n" +
	"\x03lsn\x18\x01 \x01(\x04R\x03lsn\x12\x0e\n" +
	"\x02op\x18\x02 \x01(\rR\x02op\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\rR\atableId\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04dataB\x13Z\x11./src/proto;protob\x06proto3"

var (
	file_src_proto_wal_proto_rawDescOnce sync.Once
	file_src_proto_wal_proto_rawDescData []byte
)

func file_src_proto_wal_proto_rawDescGZIP() []byte {
	file_src_proto_wal_proto_rawDescOnce.Do(func() {
		file_src_proto_wal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_proto_wal_proto_rawDesc), len(file_src_proto_wal_proto_rawDesc)))
	})
	return file_src_proto_wal_proto_rawDescData
}

var file_src_proto_wal_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_proto_wal_proto_goTypes = []any{
	(*WalRecord)(nil), // 0: proto.WalRecord
}
var file_src_proto_wal_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_proto_wal_proto_init() }
func file_src_proto_wal_proto_init() {
	if File_src_proto_wal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_proto_wal_proto_rawDesc), len(file_src_proto_wal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_proto_wal_proto_goTypes,
		DependencyIndexes: file_src_proto_wal_proto_depIdxs,
		MessageInfos:      file_src_proto_wal_proto_msgTypes,
	}.Build()
	File_src_proto_wal_proto = out.File
	file_src_proto_wal_proto_goTypes = nil
	file_src_proto_wal_proto_depIdxs = nil
}
